version: '4.0'
uid: 121262617
about:
  title: tds-community
  description: TELUS Design System Community Components
  alias: tds-community
  type: module
  target: npm
contacts:
  - type: Developer
    name: Jordan Raffoul
    slack: Jordan Raffoul
    github: jraff
    email: n6k7q6p0r9m4c1l4@telusdigital.slack.com
  - type: Designer
    name: Christina Lo
    slack: Christina L.
    github: Christina-Lo
    email: n6k7q6p0r9m4c1l4@telusdigital.slack.com
  - type: Designer
    name: Donna Vitan
    slack: donnavitan
    github: donnavitan
    email: n6k7q6p0r9m4c1l4@telusdigital.slack.com
  - type: Development Team
    name: TDS Core Team
    email: n6k7q6p0r9m4c1l4@telusdigital.slack.com
  - type: Tribe
    name: Digital Platform & Services
    slackChannel: dps-all
    email: not.applicable.see.slack.channel@telus.com
  - type: dpa
    name: Bilal Nadeem
    github: bnadeem-telus
    githubId: 45402130
  - type: dpa
    name: DougL
    github: DougTelus
    githubId: 32107656
  - type: dpa
    name: Gary Chow
    github: gkychow
    githubId: 16300159
  - type: dpa
    name: Kitty Bourne
    github: kittybourne
    githubId: 6434886
  - type: dpa
    name: Mike Bunce
    github: sketchidea
    githubId: 3803746
  - type: dpa
    name: Laurel Terlesky
    github: twirlingsky
    githubId: 22402633
  - type: Team
    name: Standards & Resources
    members_uri: 'https://github.com/orgs/telus/teams/standards-resources/members'
    repositories_uri: 'https://github.com/orgs/telus/teams/standards-resources/repositories'
references:
  - title: Github Issue Tracker
    description: >-
      TDS Community Issue Tracker board. Post bug reports or feature suggestions
      here!
    uri: 'https://github.com/telus/tds-community/issues'
  - type: git
    title: Source Code
    uri: 'https://github.com/telus/tds-community'
environments:
  - type: git
    title: Source Code
    uri: 'https://github.com/telus/tds-community'
  - type: production
    title: TDS Homepage
    description: >-
      TDS Homepage, featuring documentation on contributing to TDS or
      interacting with TDS
    uri: 'https://tds.telus.com/'
  - type: production
    title: TDS Community Components
    description: TDS Community Components documentation
    uri: 'https://tds.telus.com/community/index.html'
  - type: home
    title: Homepage
    uri: 'https://tds.telus.com/community/index.html'
schedule:
  - type: launch
    timestamp: 2018-04-30T00:00:00.000Z
  - type: public-launch
    timestamp: 2018-10-30T00:00:00.000Z
