# The docker-compose.yml describes all the services in our application. While Docker Compose is best suited for
#  multi-container applications, we can use it to simplify our interaction with Docker.
#  https://docs.docker.com/compose/overview/

# `docker-compose build` --> Build the image. Do this first.
# `docker images` --> View the image you just built

version: '3'
services:
  lib:
    container_name: tds
    build:
      context: .
      dockerfile: openshift/Dockerfile
    ports:
      - '6061:6061'
